// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace Futu.OpenApi.Pb {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class QotRequestHistoryKL {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    private static pbd::MessageDescriptor internal__static_Qot_RequestHistoryKL_C2S__Descriptor;
    private static pb::FieldAccess.FieldAccessorTable<global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S, global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S.Builder> internal__static_Qot_RequestHistoryKL_C2S__FieldAccessorTable;
    private static pbd::MessageDescriptor internal__static_Qot_RequestHistoryKL_S2C__Descriptor;
    private static pb::FieldAccess.FieldAccessorTable<global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C, global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C.Builder> internal__static_Qot_RequestHistoryKL_S2C__FieldAccessorTable;
    private static pbd::MessageDescriptor internal__static_Qot_RequestHistoryKL_Request__Descriptor;
    private static pb::FieldAccess.FieldAccessorTable<global::Futu.OpenApi.Pb.QotRequestHistoryKL.Request, global::Futu.OpenApi.Pb.QotRequestHistoryKL.Request.Builder> internal__static_Qot_RequestHistoryKL_Request__FieldAccessorTable;
    private static pbd::MessageDescriptor internal__static_Qot_RequestHistoryKL_Response__Descriptor;
    private static pb::FieldAccess.FieldAccessorTable<global::Futu.OpenApi.Pb.QotRequestHistoryKL.Response, global::Futu.OpenApi.Pb.QotRequestHistoryKL.Response.Builder> internal__static_Qot_RequestHistoryKL_Response__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static QotRequestHistoryKL() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpRb3RfUmVxdWVzdEhpc3RvcnlLTC5wcm90bxIUUW90X1JlcXVlc3RIaXN0", 
            "b3J5S0waDENvbW1vbi5wcm90bxoQUW90X0NvbW1vbi5wcm90byK3AgoDQzJT", 
            "EhwKCXJlaGFiVHlwZRgBIAIoBVIJcmVoYWJUeXBlEhYKBmtsVHlwZRgCIAIo", 
            "BVIGa2xUeXBlEjAKCHNlY3VyaXR5GAMgAigLMhQuUW90X0NvbW1vbi5TZWN1", 
            "cml0eVIIc2VjdXJpdHkSHAoJYmVnaW5UaW1lGAQgAigJUgliZWdpblRpbWUS", 
            "GAoHZW5kVGltZRgFIAIoCVIHZW5kVGltZRIgCgttYXhBY2tLTE51bRgGIAEo", 
            "BVILbWF4QWNrS0xOdW0SKgoQbmVlZEtMRmllbGRzRmxhZxgHIAEoA1IQbmVl", 
            "ZEtMRmllbGRzRmxhZxIeCgpuZXh0UmVxS2V5GAggASgMUgpuZXh0UmVxS2V5", 
            "EiIKDGV4dGVuZGVkVGltZRgJIAEoCFIMZXh0ZW5kZWRUaW1lIoIBCgNTMkMS", 
            "MAoIc2VjdXJpdHkYASACKAsyFC5Rb3RfQ29tbW9uLlNlY3VyaXR5UghzZWN1", 
            "cml0eRIpCgZrbExpc3QYAiADKAsyES5Rb3RfQ29tbW9uLktMaW5lUgZrbExp", 
            "c3QSHgoKbmV4dFJlcUtleRgDIAEoDFIKbmV4dFJlcUtleSI2CgdSZXF1ZXN0", 
            "EisKA2MycxgBIAIoCzIZLlFvdF9SZXF1ZXN0SGlzdG9yeUtMLkMyU1IDYzJz", 
            "IokBCghSZXNwb25zZRIeCgdyZXRUeXBlGAEgAigFOgQtNDAwUgdyZXRUeXBl", 
            "EhYKBnJldE1zZxgCIAEoCVIGcmV0TXNnEhgKB2VyckNvZGUYAyABKAVSB2Vy", 
            "ckNvZGUSKwoDczJjGAQgASgLMhkuUW90X1JlcXVlc3RIaXN0b3J5S0wuUzJD", 
            "UgNzMmNCSgoTY29tLmZ1dHUub3BlbmFwaS5wYlozZ2l0aHViLmNvbS9mdXR1", 
          "b3Blbi9mdGFwaTRnby9wYi9xb3RyZXF1ZXN0aGlzdG9yeWts"));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_Qot_RequestHistoryKL_C2S__Descriptor = Descriptor.MessageTypes[0];
        internal__static_Qot_RequestHistoryKL_C2S__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S, global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S.Builder>(internal__static_Qot_RequestHistoryKL_C2S__Descriptor,
                new string[] { "RehabType", "KlType", "Security", "BeginTime", "EndTime", "MaxAckKLNum", "NeedKLFieldsFlag", "NextReqKey", "ExtendedTime", });
        internal__static_Qot_RequestHistoryKL_S2C__Descriptor = Descriptor.MessageTypes[1];
        internal__static_Qot_RequestHistoryKL_S2C__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C, global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C.Builder>(internal__static_Qot_RequestHistoryKL_S2C__Descriptor,
                new string[] { "Security", "KlList", "NextReqKey", });
        internal__static_Qot_RequestHistoryKL_Request__Descriptor = Descriptor.MessageTypes[2];
        internal__static_Qot_RequestHistoryKL_Request__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::Futu.OpenApi.Pb.QotRequestHistoryKL.Request, global::Futu.OpenApi.Pb.QotRequestHistoryKL.Request.Builder>(internal__static_Qot_RequestHistoryKL_Request__Descriptor,
                new string[] { "C2S", });
        internal__static_Qot_RequestHistoryKL_Response__Descriptor = Descriptor.MessageTypes[3];
        internal__static_Qot_RequestHistoryKL_Response__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::Futu.OpenApi.Pb.QotRequestHistoryKL.Response, global::Futu.OpenApi.Pb.QotRequestHistoryKL.Response.Builder>(internal__static_Qot_RequestHistoryKL_Response__Descriptor,
                new string[] { "RetType", "RetMsg", "ErrCode", "S2C", });
        pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
        RegisterAllExtensions(registry);
        global::Futu.OpenApi.Pb.Common.RegisterAllExtensions(registry);
        global::Futu.OpenApi.Pb.QotCommon.RegisterAllExtensions(registry);
        return registry;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          global::Futu.OpenApi.Pb.Common.Descriptor, 
          global::Futu.OpenApi.Pb.QotCommon.Descriptor, 
          }, assigner);
    }
    #endregion
    
    #region Messages
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class C2S : pb::GeneratedMessage<C2S, C2S.Builder> {
      private C2S() { }
      private static readonly C2S defaultInstance = new C2S().MakeReadOnly();
      private static readonly string[] _c2SFieldNames = new string[] { "beginTime", "endTime", "extendedTime", "klType", "maxAckKLNum", "needKLFieldsFlag", "nextReqKey", "rehabType", "security" };
      private static readonly uint[] _c2SFieldTags = new uint[] { 34, 42, 72, 16, 48, 56, 66, 8, 26 };
      public static C2S DefaultInstance {
        get { return defaultInstance; }
      }
      
      public override C2S DefaultInstanceForType {
        get { return DefaultInstance; }
      }
      
      protected override C2S ThisMessage {
        get { return this; }
      }
      
      public static pbd::MessageDescriptor Descriptor {
        get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.internal__static_Qot_RequestHistoryKL_C2S__Descriptor; }
      }
      
      protected override pb::FieldAccess.FieldAccessorTable<C2S, C2S.Builder> InternalFieldAccessors {
        get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.internal__static_Qot_RequestHistoryKL_C2S__FieldAccessorTable; }
      }
      
      public const int RehabTypeFieldNumber = 1;
      private bool hasRehabType;
      private int rehabType_;
      public bool HasRehabType {
        get { return hasRehabType; }
      }
      public int RehabType {
        get { return rehabType_; }
      }
      
      public const int KlTypeFieldNumber = 2;
      private bool hasKlType;
      private int klType_;
      public bool HasKlType {
        get { return hasKlType; }
      }
      public int KlType {
        get { return klType_; }
      }
      
      public const int SecurityFieldNumber = 3;
      private bool hasSecurity;
      private global::Futu.OpenApi.Pb.QotCommon.Security security_;
      public bool HasSecurity {
        get { return hasSecurity; }
      }
      public global::Futu.OpenApi.Pb.QotCommon.Security Security {
        get { return security_ ?? global::Futu.OpenApi.Pb.QotCommon.Security.DefaultInstance; }
      }
      
      public const int BeginTimeFieldNumber = 4;
      private bool hasBeginTime;
      private string beginTime_ = "";
      public bool HasBeginTime {
        get { return hasBeginTime; }
      }
      public string BeginTime {
        get { return beginTime_; }
      }
      
      public const int EndTimeFieldNumber = 5;
      private bool hasEndTime;
      private string endTime_ = "";
      public bool HasEndTime {
        get { return hasEndTime; }
      }
      public string EndTime {
        get { return endTime_; }
      }
      
      public const int MaxAckKLNumFieldNumber = 6;
      private bool hasMaxAckKLNum;
      private int maxAckKLNum_;
      public bool HasMaxAckKLNum {
        get { return hasMaxAckKLNum; }
      }
      public int MaxAckKLNum {
        get { return maxAckKLNum_; }
      }
      
      public const int NeedKLFieldsFlagFieldNumber = 7;
      private bool hasNeedKLFieldsFlag;
      private long needKLFieldsFlag_;
      public bool HasNeedKLFieldsFlag {
        get { return hasNeedKLFieldsFlag; }
      }
      public long NeedKLFieldsFlag {
        get { return needKLFieldsFlag_; }
      }
      
      public const int NextReqKeyFieldNumber = 8;
      private bool hasNextReqKey;
      private pb::ByteString nextReqKey_ = pb::ByteString.Empty;
      public bool HasNextReqKey {
        get { return hasNextReqKey; }
      }
      public pb::ByteString NextReqKey {
        get { return nextReqKey_; }
      }
      
      public const int ExtendedTimeFieldNumber = 9;
      private bool hasExtendedTime;
      private bool extendedTime_;
      public bool HasExtendedTime {
        get { return hasExtendedTime; }
      }
      public bool ExtendedTime {
        get { return extendedTime_; }
      }
      
      public override bool IsInitialized {
        get {
          if (!hasRehabType) return false;
          if (!hasKlType) return false;
          if (!hasSecurity) return false;
          if (!hasBeginTime) return false;
          if (!hasEndTime) return false;
          if (!Security.IsInitialized) return false;
          return true;
        }
      }
      
      public override void WriteTo(pb::ICodedOutputStream output) {
        CalcSerializedSize();
        string[] field_names = _c2SFieldNames;
        if (hasRehabType) {
          output.WriteInt32(1, field_names[7], RehabType);
        }
        if (hasKlType) {
          output.WriteInt32(2, field_names[3], KlType);
        }
        if (hasSecurity) {
          output.WriteMessage(3, field_names[8], Security);
        }
        if (hasBeginTime) {
          output.WriteString(4, field_names[0], BeginTime);
        }
        if (hasEndTime) {
          output.WriteString(5, field_names[1], EndTime);
        }
        if (hasMaxAckKLNum) {
          output.WriteInt32(6, field_names[4], MaxAckKLNum);
        }
        if (hasNeedKLFieldsFlag) {
          output.WriteInt64(7, field_names[5], NeedKLFieldsFlag);
        }
        if (hasNextReqKey) {
          output.WriteBytes(8, field_names[6], NextReqKey);
        }
        if (hasExtendedTime) {
          output.WriteBool(9, field_names[2], ExtendedTime);
        }
        UnknownFields.WriteTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public override int SerializedSize {
        get {
          int size = memoizedSerializedSize;
          if (size != -1) return size;
          return CalcSerializedSize();
        }
      }
      
      private int CalcSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasRehabType) {
          size += pb::CodedOutputStream.ComputeInt32Size(1, RehabType);
        }
        if (hasKlType) {
          size += pb::CodedOutputStream.ComputeInt32Size(2, KlType);
        }
        if (hasSecurity) {
          size += pb::CodedOutputStream.ComputeMessageSize(3, Security);
        }
        if (hasBeginTime) {
          size += pb::CodedOutputStream.ComputeStringSize(4, BeginTime);
        }
        if (hasEndTime) {
          size += pb::CodedOutputStream.ComputeStringSize(5, EndTime);
        }
        if (hasMaxAckKLNum) {
          size += pb::CodedOutputStream.ComputeInt32Size(6, MaxAckKLNum);
        }
        if (hasNeedKLFieldsFlag) {
          size += pb::CodedOutputStream.ComputeInt64Size(7, NeedKLFieldsFlag);
        }
        if (hasNextReqKey) {
          size += pb::CodedOutputStream.ComputeBytesSize(8, NextReqKey);
        }
        if (hasExtendedTime) {
          size += pb::CodedOutputStream.ComputeBoolSize(9, ExtendedTime);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
      public static C2S ParseFrom(pb::ByteString data) {
        return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
      }
      public static C2S ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
      }
      public static C2S ParseFrom(byte[] data) {
        return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
      }
      public static C2S ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
      }
      public static C2S ParseFrom(global::System.IO.Stream input) {
        return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
      }
      public static C2S ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
      }
      public static C2S ParseDelimitedFrom(global::System.IO.Stream input) {
        return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
      }
      public static C2S ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
      }
      public static C2S ParseFrom(pb::ICodedInputStream input) {
        return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
      }
      public static C2S ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
      }
      private C2S MakeReadOnly() {
        return this;
      }
      
      public static Builder CreateBuilder() { return new Builder(); }
      public override Builder ToBuilder() { return CreateBuilder(this); }
      public override Builder CreateBuilderForType() { return new Builder(); }
      public static Builder CreateBuilder(C2S prototype) {
        return new Builder(prototype);
      }
      
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Builder : pb::GeneratedBuilder<C2S, Builder> {
        protected override Builder ThisBuilder {
          get { return this; }
        }
        public Builder() {
          result = DefaultInstance;
          resultIsReadOnly = true;
        }
        internal Builder(C2S cloneFrom) {
          result = cloneFrom;
          resultIsReadOnly = true;
        }
        
        private bool resultIsReadOnly;
        private C2S result;
        
        private C2S PrepareBuilder() {
          if (resultIsReadOnly) {
            C2S original = result;
            result = new C2S();
            resultIsReadOnly = false;
            MergeFrom(original);
          }
          return result;
        }
        
        public override bool IsInitialized {
          get { return result.IsInitialized; }
        }
        
        protected override C2S MessageBeingBuilt {
          get { return PrepareBuilder(); }
        }
        
        public override Builder Clear() {
          result = DefaultInstance;
          resultIsReadOnly = true;
          return this;
        }
        
        public override Builder Clone() {
          if (resultIsReadOnly) {
            return new Builder(result);
          } else {
            return new Builder().MergeFrom(result);
          }
        }
        
        public override pbd::MessageDescriptor DescriptorForType {
          get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S.Descriptor; }
        }
        
        public override C2S DefaultInstanceForType {
          get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S.DefaultInstance; }
        }
        
        public override C2S BuildPartial() {
          if (resultIsReadOnly) {
            return result;
          }
          resultIsReadOnly = true;
          return result.MakeReadOnly();
        }
        
        public override Builder MergeFrom(pb::IMessage other) {
          if (other is C2S) {
            return MergeFrom((C2S) other);
          } else {
            base.MergeFrom(other);
            return this;
          }
        }
        
        public override Builder MergeFrom(C2S other) {
          if (other == global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S.DefaultInstance) return this;
          PrepareBuilder();
          if (other.HasRehabType) {
            RehabType = other.RehabType;
          }
          if (other.HasKlType) {
            KlType = other.KlType;
          }
          if (other.HasSecurity) {
            MergeSecurity(other.Security);
          }
          if (other.HasBeginTime) {
            BeginTime = other.BeginTime;
          }
          if (other.HasEndTime) {
            EndTime = other.EndTime;
          }
          if (other.HasMaxAckKLNum) {
            MaxAckKLNum = other.MaxAckKLNum;
          }
          if (other.HasNeedKLFieldsFlag) {
            NeedKLFieldsFlag = other.NeedKLFieldsFlag;
          }
          if (other.HasNextReqKey) {
            NextReqKey = other.NextReqKey;
          }
          if (other.HasExtendedTime) {
            ExtendedTime = other.ExtendedTime;
          }
          this.MergeUnknownFields(other.UnknownFields);
          return this;
        }
        
        public override Builder MergeFrom(pb::ICodedInputStream input) {
          return MergeFrom(input, pb::ExtensionRegistry.Empty);
        }
        
        public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          PrepareBuilder();
          pb::UnknownFieldSet.Builder unknownFields = null;
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            if(tag == 0 && field_name != null) {
              int field_ordinal = global::System.Array.BinarySearch(_c2SFieldNames, field_name, global::System.StringComparer.Ordinal);
              if(field_ordinal >= 0)
                tag = _c2SFieldTags[field_ordinal];
              else {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                continue;
              }
            }
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  if (unknownFields != null) {
                    this.UnknownFields = unknownFields.Build();
                  }
                  return this;
                }
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                break;
              }
              case 8: {
                result.hasRehabType = input.ReadInt32(ref result.rehabType_);
                break;
              }
              case 16: {
                result.hasKlType = input.ReadInt32(ref result.klType_);
                break;
              }
              case 26: {
                global::Futu.OpenApi.Pb.QotCommon.Security.Builder subBuilder = global::Futu.OpenApi.Pb.QotCommon.Security.CreateBuilder();
                if (result.hasSecurity) {
                  subBuilder.MergeFrom(Security);
                }
                input.ReadMessage(subBuilder, extensionRegistry);
                Security = subBuilder.BuildPartial();
                break;
              }
              case 34: {
                result.hasBeginTime = input.ReadString(ref result.beginTime_);
                break;
              }
              case 42: {
                result.hasEndTime = input.ReadString(ref result.endTime_);
                break;
              }
              case 48: {
                result.hasMaxAckKLNum = input.ReadInt32(ref result.maxAckKLNum_);
                break;
              }
              case 56: {
                result.hasNeedKLFieldsFlag = input.ReadInt64(ref result.needKLFieldsFlag_);
                break;
              }
              case 66: {
                result.hasNextReqKey = input.ReadBytes(ref result.nextReqKey_);
                break;
              }
              case 72: {
                result.hasExtendedTime = input.ReadBool(ref result.extendedTime_);
                break;
              }
            }
          }
          
          if (unknownFields != null) {
            this.UnknownFields = unknownFields.Build();
          }
          return this;
        }
        
        
        public bool HasRehabType {
          get { return result.hasRehabType; }
        }
        public int RehabType {
          get { return result.RehabType; }
          set { SetRehabType(value); }
        }
        public Builder SetRehabType(int value) {
          PrepareBuilder();
          result.hasRehabType = true;
          result.rehabType_ = value;
          return this;
        }
        public Builder ClearRehabType() {
          PrepareBuilder();
          result.hasRehabType = false;
          result.rehabType_ = 0;
          return this;
        }
        
        public bool HasKlType {
          get { return result.hasKlType; }
        }
        public int KlType {
          get { return result.KlType; }
          set { SetKlType(value); }
        }
        public Builder SetKlType(int value) {
          PrepareBuilder();
          result.hasKlType = true;
          result.klType_ = value;
          return this;
        }
        public Builder ClearKlType() {
          PrepareBuilder();
          result.hasKlType = false;
          result.klType_ = 0;
          return this;
        }
        
        public bool HasSecurity {
         get { return result.hasSecurity; }
        }
        public global::Futu.OpenApi.Pb.QotCommon.Security Security {
          get { return result.Security; }
          set { SetSecurity(value); }
        }
        public Builder SetSecurity(global::Futu.OpenApi.Pb.QotCommon.Security value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasSecurity = true;
          result.security_ = value;
          return this;
        }
        public Builder SetSecurity(global::Futu.OpenApi.Pb.QotCommon.Security.Builder builderForValue) {
          pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
          PrepareBuilder();
          result.hasSecurity = true;
          result.security_ = builderForValue.Build();
          return this;
        }
        public Builder MergeSecurity(global::Futu.OpenApi.Pb.QotCommon.Security value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          if (result.hasSecurity &&
              result.security_ != global::Futu.OpenApi.Pb.QotCommon.Security.DefaultInstance) {
              result.security_ = global::Futu.OpenApi.Pb.QotCommon.Security.CreateBuilder(result.security_).MergeFrom(value).BuildPartial();
          } else {
            result.security_ = value;
          }
          result.hasSecurity = true;
          return this;
        }
        public Builder ClearSecurity() {
          PrepareBuilder();
          result.hasSecurity = false;
          result.security_ = null;
          return this;
        }
        
        public bool HasBeginTime {
          get { return result.hasBeginTime; }
        }
        public string BeginTime {
          get { return result.BeginTime; }
          set { SetBeginTime(value); }
        }
        public Builder SetBeginTime(string value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasBeginTime = true;
          result.beginTime_ = value;
          return this;
        }
        public Builder ClearBeginTime() {
          PrepareBuilder();
          result.hasBeginTime = false;
          result.beginTime_ = "";
          return this;
        }
        
        public bool HasEndTime {
          get { return result.hasEndTime; }
        }
        public string EndTime {
          get { return result.EndTime; }
          set { SetEndTime(value); }
        }
        public Builder SetEndTime(string value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasEndTime = true;
          result.endTime_ = value;
          return this;
        }
        public Builder ClearEndTime() {
          PrepareBuilder();
          result.hasEndTime = false;
          result.endTime_ = "";
          return this;
        }
        
        public bool HasMaxAckKLNum {
          get { return result.hasMaxAckKLNum; }
        }
        public int MaxAckKLNum {
          get { return result.MaxAckKLNum; }
          set { SetMaxAckKLNum(value); }
        }
        public Builder SetMaxAckKLNum(int value) {
          PrepareBuilder();
          result.hasMaxAckKLNum = true;
          result.maxAckKLNum_ = value;
          return this;
        }
        public Builder ClearMaxAckKLNum() {
          PrepareBuilder();
          result.hasMaxAckKLNum = false;
          result.maxAckKLNum_ = 0;
          return this;
        }
        
        public bool HasNeedKLFieldsFlag {
          get { return result.hasNeedKLFieldsFlag; }
        }
        public long NeedKLFieldsFlag {
          get { return result.NeedKLFieldsFlag; }
          set { SetNeedKLFieldsFlag(value); }
        }
        public Builder SetNeedKLFieldsFlag(long value) {
          PrepareBuilder();
          result.hasNeedKLFieldsFlag = true;
          result.needKLFieldsFlag_ = value;
          return this;
        }
        public Builder ClearNeedKLFieldsFlag() {
          PrepareBuilder();
          result.hasNeedKLFieldsFlag = false;
          result.needKLFieldsFlag_ = 0L;
          return this;
        }
        
        public bool HasNextReqKey {
          get { return result.hasNextReqKey; }
        }
        public pb::ByteString NextReqKey {
          get { return result.NextReqKey; }
          set { SetNextReqKey(value); }
        }
        public Builder SetNextReqKey(pb::ByteString value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasNextReqKey = true;
          result.nextReqKey_ = value;
          return this;
        }
        public Builder ClearNextReqKey() {
          PrepareBuilder();
          result.hasNextReqKey = false;
          result.nextReqKey_ = pb::ByteString.Empty;
          return this;
        }
        
        public bool HasExtendedTime {
          get { return result.hasExtendedTime; }
        }
        public bool ExtendedTime {
          get { return result.ExtendedTime; }
          set { SetExtendedTime(value); }
        }
        public Builder SetExtendedTime(bool value) {
          PrepareBuilder();
          result.hasExtendedTime = true;
          result.extendedTime_ = value;
          return this;
        }
        public Builder ClearExtendedTime() {
          PrepareBuilder();
          result.hasExtendedTime = false;
          result.extendedTime_ = false;
          return this;
        }
      }
      static C2S() {
        object.ReferenceEquals(global::Futu.OpenApi.Pb.QotRequestHistoryKL.Descriptor, null);
      }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class S2C : pb::GeneratedMessage<S2C, S2C.Builder> {
      private S2C() { }
      private static readonly S2C defaultInstance = new S2C().MakeReadOnly();
      private static readonly string[] _s2CFieldNames = new string[] { "klList", "nextReqKey", "security" };
      private static readonly uint[] _s2CFieldTags = new uint[] { 18, 26, 10 };
      public static S2C DefaultInstance {
        get { return defaultInstance; }
      }
      
      public override S2C DefaultInstanceForType {
        get { return DefaultInstance; }
      }
      
      protected override S2C ThisMessage {
        get { return this; }
      }
      
      public static pbd::MessageDescriptor Descriptor {
        get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.internal__static_Qot_RequestHistoryKL_S2C__Descriptor; }
      }
      
      protected override pb::FieldAccess.FieldAccessorTable<S2C, S2C.Builder> InternalFieldAccessors {
        get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.internal__static_Qot_RequestHistoryKL_S2C__FieldAccessorTable; }
      }
      
      public const int SecurityFieldNumber = 1;
      private bool hasSecurity;
      private global::Futu.OpenApi.Pb.QotCommon.Security security_;
      public bool HasSecurity {
        get { return hasSecurity; }
      }
      public global::Futu.OpenApi.Pb.QotCommon.Security Security {
        get { return security_ ?? global::Futu.OpenApi.Pb.QotCommon.Security.DefaultInstance; }
      }
      
      public const int KlListFieldNumber = 2;
      private pbc::PopsicleList<global::Futu.OpenApi.Pb.QotCommon.KLine> klList_ = new pbc::PopsicleList<global::Futu.OpenApi.Pb.QotCommon.KLine>();
      public scg::IList<global::Futu.OpenApi.Pb.QotCommon.KLine> KlListList {
        get { return klList_; }
      }
      public int KlListCount {
        get { return klList_.Count; }
      }
      public global::Futu.OpenApi.Pb.QotCommon.KLine GetKlList(int index) {
        return klList_[index];
      }
      
      public const int NextReqKeyFieldNumber = 3;
      private bool hasNextReqKey;
      private pb::ByteString nextReqKey_ = pb::ByteString.Empty;
      public bool HasNextReqKey {
        get { return hasNextReqKey; }
      }
      public pb::ByteString NextReqKey {
        get { return nextReqKey_; }
      }
      
      public override bool IsInitialized {
        get {
          if (!hasSecurity) return false;
          if (!Security.IsInitialized) return false;
          foreach (global::Futu.OpenApi.Pb.QotCommon.KLine element in KlListList) {
            if (!element.IsInitialized) return false;
          }
          return true;
        }
      }
      
      public override void WriteTo(pb::ICodedOutputStream output) {
        CalcSerializedSize();
        string[] field_names = _s2CFieldNames;
        if (hasSecurity) {
          output.WriteMessage(1, field_names[2], Security);
        }
        if (klList_.Count > 0) {
          output.WriteMessageArray(2, field_names[0], klList_);
        }
        if (hasNextReqKey) {
          output.WriteBytes(3, field_names[1], NextReqKey);
        }
        UnknownFields.WriteTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public override int SerializedSize {
        get {
          int size = memoizedSerializedSize;
          if (size != -1) return size;
          return CalcSerializedSize();
        }
      }
      
      private int CalcSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasSecurity) {
          size += pb::CodedOutputStream.ComputeMessageSize(1, Security);
        }
        foreach (global::Futu.OpenApi.Pb.QotCommon.KLine element in KlListList) {
          size += pb::CodedOutputStream.ComputeMessageSize(2, element);
        }
        if (hasNextReqKey) {
          size += pb::CodedOutputStream.ComputeBytesSize(3, NextReqKey);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
      public static S2C ParseFrom(pb::ByteString data) {
        return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
      }
      public static S2C ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
      }
      public static S2C ParseFrom(byte[] data) {
        return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
      }
      public static S2C ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
      }
      public static S2C ParseFrom(global::System.IO.Stream input) {
        return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
      }
      public static S2C ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
      }
      public static S2C ParseDelimitedFrom(global::System.IO.Stream input) {
        return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
      }
      public static S2C ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
      }
      public static S2C ParseFrom(pb::ICodedInputStream input) {
        return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
      }
      public static S2C ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
      }
      private S2C MakeReadOnly() {
        klList_.MakeReadOnly();
        return this;
      }
      
      public static Builder CreateBuilder() { return new Builder(); }
      public override Builder ToBuilder() { return CreateBuilder(this); }
      public override Builder CreateBuilderForType() { return new Builder(); }
      public static Builder CreateBuilder(S2C prototype) {
        return new Builder(prototype);
      }
      
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Builder : pb::GeneratedBuilder<S2C, Builder> {
        protected override Builder ThisBuilder {
          get { return this; }
        }
        public Builder() {
          result = DefaultInstance;
          resultIsReadOnly = true;
        }
        internal Builder(S2C cloneFrom) {
          result = cloneFrom;
          resultIsReadOnly = true;
        }
        
        private bool resultIsReadOnly;
        private S2C result;
        
        private S2C PrepareBuilder() {
          if (resultIsReadOnly) {
            S2C original = result;
            result = new S2C();
            resultIsReadOnly = false;
            MergeFrom(original);
          }
          return result;
        }
        
        public override bool IsInitialized {
          get { return result.IsInitialized; }
        }
        
        protected override S2C MessageBeingBuilt {
          get { return PrepareBuilder(); }
        }
        
        public override Builder Clear() {
          result = DefaultInstance;
          resultIsReadOnly = true;
          return this;
        }
        
        public override Builder Clone() {
          if (resultIsReadOnly) {
            return new Builder(result);
          } else {
            return new Builder().MergeFrom(result);
          }
        }
        
        public override pbd::MessageDescriptor DescriptorForType {
          get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C.Descriptor; }
        }
        
        public override S2C DefaultInstanceForType {
          get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C.DefaultInstance; }
        }
        
        public override S2C BuildPartial() {
          if (resultIsReadOnly) {
            return result;
          }
          resultIsReadOnly = true;
          return result.MakeReadOnly();
        }
        
        public override Builder MergeFrom(pb::IMessage other) {
          if (other is S2C) {
            return MergeFrom((S2C) other);
          } else {
            base.MergeFrom(other);
            return this;
          }
        }
        
        public override Builder MergeFrom(S2C other) {
          if (other == global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C.DefaultInstance) return this;
          PrepareBuilder();
          if (other.HasSecurity) {
            MergeSecurity(other.Security);
          }
          if (other.klList_.Count != 0) {
            result.klList_.Add(other.klList_);
          }
          if (other.HasNextReqKey) {
            NextReqKey = other.NextReqKey;
          }
          this.MergeUnknownFields(other.UnknownFields);
          return this;
        }
        
        public override Builder MergeFrom(pb::ICodedInputStream input) {
          return MergeFrom(input, pb::ExtensionRegistry.Empty);
        }
        
        public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          PrepareBuilder();
          pb::UnknownFieldSet.Builder unknownFields = null;
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            if(tag == 0 && field_name != null) {
              int field_ordinal = global::System.Array.BinarySearch(_s2CFieldNames, field_name, global::System.StringComparer.Ordinal);
              if(field_ordinal >= 0)
                tag = _s2CFieldTags[field_ordinal];
              else {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                continue;
              }
            }
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  if (unknownFields != null) {
                    this.UnknownFields = unknownFields.Build();
                  }
                  return this;
                }
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                break;
              }
              case 10: {
                global::Futu.OpenApi.Pb.QotCommon.Security.Builder subBuilder = global::Futu.OpenApi.Pb.QotCommon.Security.CreateBuilder();
                if (result.hasSecurity) {
                  subBuilder.MergeFrom(Security);
                }
                input.ReadMessage(subBuilder, extensionRegistry);
                Security = subBuilder.BuildPartial();
                break;
              }
              case 18: {
                input.ReadMessageArray(tag, field_name, result.klList_, global::Futu.OpenApi.Pb.QotCommon.KLine.DefaultInstance, extensionRegistry);
                break;
              }
              case 26: {
                result.hasNextReqKey = input.ReadBytes(ref result.nextReqKey_);
                break;
              }
            }
          }
          
          if (unknownFields != null) {
            this.UnknownFields = unknownFields.Build();
          }
          return this;
        }
        
        
        public bool HasSecurity {
         get { return result.hasSecurity; }
        }
        public global::Futu.OpenApi.Pb.QotCommon.Security Security {
          get { return result.Security; }
          set { SetSecurity(value); }
        }
        public Builder SetSecurity(global::Futu.OpenApi.Pb.QotCommon.Security value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasSecurity = true;
          result.security_ = value;
          return this;
        }
        public Builder SetSecurity(global::Futu.OpenApi.Pb.QotCommon.Security.Builder builderForValue) {
          pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
          PrepareBuilder();
          result.hasSecurity = true;
          result.security_ = builderForValue.Build();
          return this;
        }
        public Builder MergeSecurity(global::Futu.OpenApi.Pb.QotCommon.Security value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          if (result.hasSecurity &&
              result.security_ != global::Futu.OpenApi.Pb.QotCommon.Security.DefaultInstance) {
              result.security_ = global::Futu.OpenApi.Pb.QotCommon.Security.CreateBuilder(result.security_).MergeFrom(value).BuildPartial();
          } else {
            result.security_ = value;
          }
          result.hasSecurity = true;
          return this;
        }
        public Builder ClearSecurity() {
          PrepareBuilder();
          result.hasSecurity = false;
          result.security_ = null;
          return this;
        }
        
        public pbc::IPopsicleList<global::Futu.OpenApi.Pb.QotCommon.KLine> KlListList {
          get { return PrepareBuilder().klList_; }
        }
        public int KlListCount {
          get { return result.KlListCount; }
        }
        public global::Futu.OpenApi.Pb.QotCommon.KLine GetKlList(int index) {
          return result.GetKlList(index);
        }
        public Builder SetKlList(int index, global::Futu.OpenApi.Pb.QotCommon.KLine value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.klList_[index] = value;
          return this;
        }
        public Builder SetKlList(int index, global::Futu.OpenApi.Pb.QotCommon.KLine.Builder builderForValue) {
          pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
          PrepareBuilder();
          result.klList_[index] = builderForValue.Build();
          return this;
        }
        public Builder AddKlList(global::Futu.OpenApi.Pb.QotCommon.KLine value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.klList_.Add(value);
          return this;
        }
        public Builder AddKlList(global::Futu.OpenApi.Pb.QotCommon.KLine.Builder builderForValue) {
          pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
          PrepareBuilder();
          result.klList_.Add(builderForValue.Build());
          return this;
        }
        public Builder AddRangeKlList(scg::IEnumerable<global::Futu.OpenApi.Pb.QotCommon.KLine> values) {
          PrepareBuilder();
          result.klList_.Add(values);
          return this;
        }
        public Builder ClearKlList() {
          PrepareBuilder();
          result.klList_.Clear();
          return this;
        }
        
        public bool HasNextReqKey {
          get { return result.hasNextReqKey; }
        }
        public pb::ByteString NextReqKey {
          get { return result.NextReqKey; }
          set { SetNextReqKey(value); }
        }
        public Builder SetNextReqKey(pb::ByteString value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasNextReqKey = true;
          result.nextReqKey_ = value;
          return this;
        }
        public Builder ClearNextReqKey() {
          PrepareBuilder();
          result.hasNextReqKey = false;
          result.nextReqKey_ = pb::ByteString.Empty;
          return this;
        }
      }
      static S2C() {
        object.ReferenceEquals(global::Futu.OpenApi.Pb.QotRequestHistoryKL.Descriptor, null);
      }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Request : pb::GeneratedMessage<Request, Request.Builder> {
      private Request() { }
      private static readonly Request defaultInstance = new Request().MakeReadOnly();
      private static readonly string[] _requestFieldNames = new string[] { "c2s" };
      private static readonly uint[] _requestFieldTags = new uint[] { 10 };
      public static Request DefaultInstance {
        get { return defaultInstance; }
      }
      
      public override Request DefaultInstanceForType {
        get { return DefaultInstance; }
      }
      
      protected override Request ThisMessage {
        get { return this; }
      }
      
      public static pbd::MessageDescriptor Descriptor {
        get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.internal__static_Qot_RequestHistoryKL_Request__Descriptor; }
      }
      
      protected override pb::FieldAccess.FieldAccessorTable<Request, Request.Builder> InternalFieldAccessors {
        get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.internal__static_Qot_RequestHistoryKL_Request__FieldAccessorTable; }
      }
      
      public const int C2SFieldNumber = 1;
      private bool hasC2S;
      private global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S c2S_;
      public bool HasC2S {
        get { return hasC2S; }
      }
      public global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S C2S {
        get { return c2S_ ?? global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S.DefaultInstance; }
      }
      
      public override bool IsInitialized {
        get {
          if (!hasC2S) return false;
          if (!C2S.IsInitialized) return false;
          return true;
        }
      }
      
      public override void WriteTo(pb::ICodedOutputStream output) {
        CalcSerializedSize();
        string[] field_names = _requestFieldNames;
        if (hasC2S) {
          output.WriteMessage(1, field_names[0], C2S);
        }
        UnknownFields.WriteTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public override int SerializedSize {
        get {
          int size = memoizedSerializedSize;
          if (size != -1) return size;
          return CalcSerializedSize();
        }
      }
      
      private int CalcSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasC2S) {
          size += pb::CodedOutputStream.ComputeMessageSize(1, C2S);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
      public static Request ParseFrom(pb::ByteString data) {
        return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
      }
      public static Request ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
      }
      public static Request ParseFrom(byte[] data) {
        return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
      }
      public static Request ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
      }
      public static Request ParseFrom(global::System.IO.Stream input) {
        return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
      }
      public static Request ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
      }
      public static Request ParseDelimitedFrom(global::System.IO.Stream input) {
        return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
      }
      public static Request ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
      }
      public static Request ParseFrom(pb::ICodedInputStream input) {
        return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
      }
      public static Request ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
      }
      private Request MakeReadOnly() {
        return this;
      }
      
      public static Builder CreateBuilder() { return new Builder(); }
      public override Builder ToBuilder() { return CreateBuilder(this); }
      public override Builder CreateBuilderForType() { return new Builder(); }
      public static Builder CreateBuilder(Request prototype) {
        return new Builder(prototype);
      }
      
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Builder : pb::GeneratedBuilder<Request, Builder> {
        protected override Builder ThisBuilder {
          get { return this; }
        }
        public Builder() {
          result = DefaultInstance;
          resultIsReadOnly = true;
        }
        internal Builder(Request cloneFrom) {
          result = cloneFrom;
          resultIsReadOnly = true;
        }
        
        private bool resultIsReadOnly;
        private Request result;
        
        private Request PrepareBuilder() {
          if (resultIsReadOnly) {
            Request original = result;
            result = new Request();
            resultIsReadOnly = false;
            MergeFrom(original);
          }
          return result;
        }
        
        public override bool IsInitialized {
          get { return result.IsInitialized; }
        }
        
        protected override Request MessageBeingBuilt {
          get { return PrepareBuilder(); }
        }
        
        public override Builder Clear() {
          result = DefaultInstance;
          resultIsReadOnly = true;
          return this;
        }
        
        public override Builder Clone() {
          if (resultIsReadOnly) {
            return new Builder(result);
          } else {
            return new Builder().MergeFrom(result);
          }
        }
        
        public override pbd::MessageDescriptor DescriptorForType {
          get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.Request.Descriptor; }
        }
        
        public override Request DefaultInstanceForType {
          get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.Request.DefaultInstance; }
        }
        
        public override Request BuildPartial() {
          if (resultIsReadOnly) {
            return result;
          }
          resultIsReadOnly = true;
          return result.MakeReadOnly();
        }
        
        public override Builder MergeFrom(pb::IMessage other) {
          if (other is Request) {
            return MergeFrom((Request) other);
          } else {
            base.MergeFrom(other);
            return this;
          }
        }
        
        public override Builder MergeFrom(Request other) {
          if (other == global::Futu.OpenApi.Pb.QotRequestHistoryKL.Request.DefaultInstance) return this;
          PrepareBuilder();
          if (other.HasC2S) {
            MergeC2S(other.C2S);
          }
          this.MergeUnknownFields(other.UnknownFields);
          return this;
        }
        
        public override Builder MergeFrom(pb::ICodedInputStream input) {
          return MergeFrom(input, pb::ExtensionRegistry.Empty);
        }
        
        public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          PrepareBuilder();
          pb::UnknownFieldSet.Builder unknownFields = null;
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            if(tag == 0 && field_name != null) {
              int field_ordinal = global::System.Array.BinarySearch(_requestFieldNames, field_name, global::System.StringComparer.Ordinal);
              if(field_ordinal >= 0)
                tag = _requestFieldTags[field_ordinal];
              else {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                continue;
              }
            }
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  if (unknownFields != null) {
                    this.UnknownFields = unknownFields.Build();
                  }
                  return this;
                }
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                break;
              }
              case 10: {
                global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S.Builder subBuilder = global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S.CreateBuilder();
                if (result.hasC2S) {
                  subBuilder.MergeFrom(C2S);
                }
                input.ReadMessage(subBuilder, extensionRegistry);
                C2S = subBuilder.BuildPartial();
                break;
              }
            }
          }
          
          if (unknownFields != null) {
            this.UnknownFields = unknownFields.Build();
          }
          return this;
        }
        
        
        public bool HasC2S {
         get { return result.hasC2S; }
        }
        public global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S C2S {
          get { return result.C2S; }
          set { SetC2S(value); }
        }
        public Builder SetC2S(global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasC2S = true;
          result.c2S_ = value;
          return this;
        }
        public Builder SetC2S(global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S.Builder builderForValue) {
          pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
          PrepareBuilder();
          result.hasC2S = true;
          result.c2S_ = builderForValue.Build();
          return this;
        }
        public Builder MergeC2S(global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          if (result.hasC2S &&
              result.c2S_ != global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S.DefaultInstance) {
              result.c2S_ = global::Futu.OpenApi.Pb.QotRequestHistoryKL.C2S.CreateBuilder(result.c2S_).MergeFrom(value).BuildPartial();
          } else {
            result.c2S_ = value;
          }
          result.hasC2S = true;
          return this;
        }
        public Builder ClearC2S() {
          PrepareBuilder();
          result.hasC2S = false;
          result.c2S_ = null;
          return this;
        }
      }
      static Request() {
        object.ReferenceEquals(global::Futu.OpenApi.Pb.QotRequestHistoryKL.Descriptor, null);
      }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Response : pb::GeneratedMessage<Response, Response.Builder> {
      private Response() { }
      private static readonly Response defaultInstance = new Response().MakeReadOnly();
      private static readonly string[] _responseFieldNames = new string[] { "errCode", "retMsg", "retType", "s2c" };
      private static readonly uint[] _responseFieldTags = new uint[] { 24, 18, 8, 34 };
      public static Response DefaultInstance {
        get { return defaultInstance; }
      }
      
      public override Response DefaultInstanceForType {
        get { return DefaultInstance; }
      }
      
      protected override Response ThisMessage {
        get { return this; }
      }
      
      public static pbd::MessageDescriptor Descriptor {
        get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.internal__static_Qot_RequestHistoryKL_Response__Descriptor; }
      }
      
      protected override pb::FieldAccess.FieldAccessorTable<Response, Response.Builder> InternalFieldAccessors {
        get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.internal__static_Qot_RequestHistoryKL_Response__FieldAccessorTable; }
      }
      
      public const int RetTypeFieldNumber = 1;
      private bool hasRetType;
      private int retType_ = -400;
      public bool HasRetType {
        get { return hasRetType; }
      }
      public int RetType {
        get { return retType_; }
      }
      
      public const int RetMsgFieldNumber = 2;
      private bool hasRetMsg;
      private string retMsg_ = "";
      public bool HasRetMsg {
        get { return hasRetMsg; }
      }
      public string RetMsg {
        get { return retMsg_; }
      }
      
      public const int ErrCodeFieldNumber = 3;
      private bool hasErrCode;
      private int errCode_;
      public bool HasErrCode {
        get { return hasErrCode; }
      }
      public int ErrCode {
        get { return errCode_; }
      }
      
      public const int S2CFieldNumber = 4;
      private bool hasS2C;
      private global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C s2C_;
      public bool HasS2C {
        get { return hasS2C; }
      }
      public global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C S2C {
        get { return s2C_ ?? global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C.DefaultInstance; }
      }
      
      public override bool IsInitialized {
        get {
          if (!hasRetType) return false;
          if (HasS2C) {
            if (!S2C.IsInitialized) return false;
          }
          return true;
        }
      }
      
      public override void WriteTo(pb::ICodedOutputStream output) {
        CalcSerializedSize();
        string[] field_names = _responseFieldNames;
        if (hasRetType) {
          output.WriteInt32(1, field_names[2], RetType);
        }
        if (hasRetMsg) {
          output.WriteString(2, field_names[1], RetMsg);
        }
        if (hasErrCode) {
          output.WriteInt32(3, field_names[0], ErrCode);
        }
        if (hasS2C) {
          output.WriteMessage(4, field_names[3], S2C);
        }
        UnknownFields.WriteTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public override int SerializedSize {
        get {
          int size = memoizedSerializedSize;
          if (size != -1) return size;
          return CalcSerializedSize();
        }
      }
      
      private int CalcSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasRetType) {
          size += pb::CodedOutputStream.ComputeInt32Size(1, RetType);
        }
        if (hasRetMsg) {
          size += pb::CodedOutputStream.ComputeStringSize(2, RetMsg);
        }
        if (hasErrCode) {
          size += pb::CodedOutputStream.ComputeInt32Size(3, ErrCode);
        }
        if (hasS2C) {
          size += pb::CodedOutputStream.ComputeMessageSize(4, S2C);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
      public static Response ParseFrom(pb::ByteString data) {
        return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
      }
      public static Response ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
      }
      public static Response ParseFrom(byte[] data) {
        return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
      }
      public static Response ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
      }
      public static Response ParseFrom(global::System.IO.Stream input) {
        return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
      }
      public static Response ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
      }
      public static Response ParseDelimitedFrom(global::System.IO.Stream input) {
        return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
      }
      public static Response ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
      }
      public static Response ParseFrom(pb::ICodedInputStream input) {
        return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
      }
      public static Response ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
      }
      private Response MakeReadOnly() {
        return this;
      }
      
      public static Builder CreateBuilder() { return new Builder(); }
      public override Builder ToBuilder() { return CreateBuilder(this); }
      public override Builder CreateBuilderForType() { return new Builder(); }
      public static Builder CreateBuilder(Response prototype) {
        return new Builder(prototype);
      }
      
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Builder : pb::GeneratedBuilder<Response, Builder> {
        protected override Builder ThisBuilder {
          get { return this; }
        }
        public Builder() {
          result = DefaultInstance;
          resultIsReadOnly = true;
        }
        internal Builder(Response cloneFrom) {
          result = cloneFrom;
          resultIsReadOnly = true;
        }
        
        private bool resultIsReadOnly;
        private Response result;
        
        private Response PrepareBuilder() {
          if (resultIsReadOnly) {
            Response original = result;
            result = new Response();
            resultIsReadOnly = false;
            MergeFrom(original);
          }
          return result;
        }
        
        public override bool IsInitialized {
          get { return result.IsInitialized; }
        }
        
        protected override Response MessageBeingBuilt {
          get { return PrepareBuilder(); }
        }
        
        public override Builder Clear() {
          result = DefaultInstance;
          resultIsReadOnly = true;
          return this;
        }
        
        public override Builder Clone() {
          if (resultIsReadOnly) {
            return new Builder(result);
          } else {
            return new Builder().MergeFrom(result);
          }
        }
        
        public override pbd::MessageDescriptor DescriptorForType {
          get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.Response.Descriptor; }
        }
        
        public override Response DefaultInstanceForType {
          get { return global::Futu.OpenApi.Pb.QotRequestHistoryKL.Response.DefaultInstance; }
        }
        
        public override Response BuildPartial() {
          if (resultIsReadOnly) {
            return result;
          }
          resultIsReadOnly = true;
          return result.MakeReadOnly();
        }
        
        public override Builder MergeFrom(pb::IMessage other) {
          if (other is Response) {
            return MergeFrom((Response) other);
          } else {
            base.MergeFrom(other);
            return this;
          }
        }
        
        public override Builder MergeFrom(Response other) {
          if (other == global::Futu.OpenApi.Pb.QotRequestHistoryKL.Response.DefaultInstance) return this;
          PrepareBuilder();
          if (other.HasRetType) {
            RetType = other.RetType;
          }
          if (other.HasRetMsg) {
            RetMsg = other.RetMsg;
          }
          if (other.HasErrCode) {
            ErrCode = other.ErrCode;
          }
          if (other.HasS2C) {
            MergeS2C(other.S2C);
          }
          this.MergeUnknownFields(other.UnknownFields);
          return this;
        }
        
        public override Builder MergeFrom(pb::ICodedInputStream input) {
          return MergeFrom(input, pb::ExtensionRegistry.Empty);
        }
        
        public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          PrepareBuilder();
          pb::UnknownFieldSet.Builder unknownFields = null;
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            if(tag == 0 && field_name != null) {
              int field_ordinal = global::System.Array.BinarySearch(_responseFieldNames, field_name, global::System.StringComparer.Ordinal);
              if(field_ordinal >= 0)
                tag = _responseFieldTags[field_ordinal];
              else {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                continue;
              }
            }
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  if (unknownFields != null) {
                    this.UnknownFields = unknownFields.Build();
                  }
                  return this;
                }
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                break;
              }
              case 8: {
                result.hasRetType = input.ReadInt32(ref result.retType_);
                break;
              }
              case 18: {
                result.hasRetMsg = input.ReadString(ref result.retMsg_);
                break;
              }
              case 24: {
                result.hasErrCode = input.ReadInt32(ref result.errCode_);
                break;
              }
              case 34: {
                global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C.Builder subBuilder = global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C.CreateBuilder();
                if (result.hasS2C) {
                  subBuilder.MergeFrom(S2C);
                }
                input.ReadMessage(subBuilder, extensionRegistry);
                S2C = subBuilder.BuildPartial();
                break;
              }
            }
          }
          
          if (unknownFields != null) {
            this.UnknownFields = unknownFields.Build();
          }
          return this;
        }
        
        
        public bool HasRetType {
          get { return result.hasRetType; }
        }
        public int RetType {
          get { return result.RetType; }
          set { SetRetType(value); }
        }
        public Builder SetRetType(int value) {
          PrepareBuilder();
          result.hasRetType = true;
          result.retType_ = value;
          return this;
        }
        public Builder ClearRetType() {
          PrepareBuilder();
          result.hasRetType = false;
          result.retType_ = -400;
          return this;
        }
        
        public bool HasRetMsg {
          get { return result.hasRetMsg; }
        }
        public string RetMsg {
          get { return result.RetMsg; }
          set { SetRetMsg(value); }
        }
        public Builder SetRetMsg(string value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasRetMsg = true;
          result.retMsg_ = value;
          return this;
        }
        public Builder ClearRetMsg() {
          PrepareBuilder();
          result.hasRetMsg = false;
          result.retMsg_ = "";
          return this;
        }
        
        public bool HasErrCode {
          get { return result.hasErrCode; }
        }
        public int ErrCode {
          get { return result.ErrCode; }
          set { SetErrCode(value); }
        }
        public Builder SetErrCode(int value) {
          PrepareBuilder();
          result.hasErrCode = true;
          result.errCode_ = value;
          return this;
        }
        public Builder ClearErrCode() {
          PrepareBuilder();
          result.hasErrCode = false;
          result.errCode_ = 0;
          return this;
        }
        
        public bool HasS2C {
         get { return result.hasS2C; }
        }
        public global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C S2C {
          get { return result.S2C; }
          set { SetS2C(value); }
        }
        public Builder SetS2C(global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasS2C = true;
          result.s2C_ = value;
          return this;
        }
        public Builder SetS2C(global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C.Builder builderForValue) {
          pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
          PrepareBuilder();
          result.hasS2C = true;
          result.s2C_ = builderForValue.Build();
          return this;
        }
        public Builder MergeS2C(global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          if (result.hasS2C &&
              result.s2C_ != global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C.DefaultInstance) {
              result.s2C_ = global::Futu.OpenApi.Pb.QotRequestHistoryKL.S2C.CreateBuilder(result.s2C_).MergeFrom(value).BuildPartial();
          } else {
            result.s2C_ = value;
          }
          result.hasS2C = true;
          return this;
        }
        public Builder ClearS2C() {
          PrepareBuilder();
          result.hasS2C = false;
          result.s2C_ = null;
          return this;
        }
      }
      static Response() {
        object.ReferenceEquals(global::Futu.OpenApi.Pb.QotRequestHistoryKL.Descriptor, null);
      }
    }
    
    #endregion
    
  }
}

#endregion Designer generated code
